### PR TITLE
Setup directory tree to run grub-mkconfig

### PR DESCRIPTION
**Pull request by johnramsden**
## Setup directory tree to run grub-mkconfig

Upon activate if `org.zedenv.grub:bootonzfs` property set, mount ZFS BEs to `${grubboot}/zfsenv/zedenv-${boot_env}`.

After mkconfig they will be unmounted.

Now grub-mkconfig can walk the tree and generate the config as discussed in #1

Mount regular kernel directories to `${grubboot}/env/zedenv-${boot_env}`

- [x] Mount datasets to `${grubboot}/zfsenv/zedenv-${boot_env}` if `bootonzfs=yes`
- [ ] Have generator create `grub.cfg`

### CODE REVIEW

**Comment by johnramsden** [comment]
cc @zdykstra As of 6b344d6e1c7547f00f239eae5bc3f7341d7a120e, datasets are being mounted if boot is on ZFS.

Here's the relevant verbose output:

```
zedenv activate -v -b grub default-3
```

```
Activating Boot Environment: default-3

Configuring boot environment bootloader with grub

Checking prop: 'org.zedenv.grub:boot'
Checking prop: 'org.zedenv.grub:bootonzfs'
org.zedenv.grub:bootonzfs=yes.

Using plugin grub

Boot environment default-3 exists'

[REDACTED]

Going over list [{'name': 'vault/sys/wooly/ROOT/default-3'}, {'name': 'vault/sys/wooly/ROOT/default-4'}, {'name': 'vault/sys/wooly/ROOT/linux-4.16.11-1'}, {'name': 'vault/sys/wooly/ROOT/linux-4.16.13-1'}].

Setting up vault/sys/wooly/ROOT/default-3.

Mounting boot environment 'default-3'.

Mountpoint '/mnt/boot/zfsenv/zedenv-default-3' given, using as mountpoint.

Mounted dataset to '/mnt/boot/zfsenv/zedenv-default-3'.

Setting up vault/sys/wooly/ROOT/default-4.

Mounting boot environment 'default-4'.

Mountpoint '/mnt/boot/zfsenv/zedenv-default-4' given, using as mountpoint.

Mounted dataset to '/mnt/boot/zfsenv/zedenv-default-4'.

Setting up vault/sys/wooly/ROOT/linux-4.16.11-1.

Mounting boot environment 'linux-4.16.11-1'.

Mountpoint '/mnt/boot/zfsenv/zedenv-linux-4.16.11-1' given, using as mountpoint.

Mounted dataset to '/mnt/boot/zfsenv/zedenv-linux-4.16.11-1'.

Setting up vault/sys/wooly/ROOT/linux-4.16.13-1.

Mounting boot environment 'linux-4.16.13-1'.

Mountpoint '/mnt/boot/zfsenv/zedenv-linux-4.16.13-1' given, using as mountpoint.

Mounted dataset to '/mnt/boot/zfsenv/zedenv-linux-4.16.13-1'.
```

**Comment by zdykstra** [comment]
I'm not sure what I'm missing here. I've set 

`locker/ROOT/default  org.zedenv.grub:bootonzfs  yes                                      local`

on all of my environments, but I'm not seeing the same dataset mounting as you.

```
[zdykstra@void-zfs-dev zedenv-grub]$ sudo zedenv activate default -v
Activating Boot Environment: default

Boot environment default exists'

Disabled automount for locker/ROOT/test-1

Disabled automount for locker/ROOT/test-2

Disabled automount for locker/ROOT/upgrade-test

Promoted locker/ROOT/default
```

Do I need to enable anything else? Would it be possible to simply detect if /boot is on ZFS, or are there edge cases I'm not thinking of?

**Comment by johnramsden** [comment]
I usually set the property on my BE root, ie `locker/ROOT` so it's just inherited by all of the datasets. 

You then need to run it with `-b grub`, or set `org.zedenv:bootloader=grub`. 

I've also been running this off of the master of `zedenv` and there might be some changes it's dependent on which is causing the problem. I'll push the latest code up when I get a chance.

**Comment by zdykstra** [comment]
Ahh, I missed that I needed to turn on grub. I'll try again shortly and
report back what I see.

**Comment by johnramsden** [comment]
Yea, you will need the latest master https://github.com/johnramsden/zedenv/commit/bf3783f5a5f86ee6021f8c704ae426f73cdf73cd

**Comment by johnramsden** [comment]
Just to note, I had commented out the code that runs the `grub_mkconfig`, because I didn't want it running on my dev machine but if you wanted to try it, it can be uncommented.

https://github.com/johnramsden/zedenv-grub/blob/ca45f5f64934df46f8fc51ecde9502a5b84f198b/zedenv_grub/grub.py#L303-L309

**Comment by zdykstra** [comment]
I've bumped my zedenv commit and run through the grub plugin, without allowing it to make a grub.cfg. Nothing obvious for problems is jumping out at me. This looks like it's ready for the the grub generators for a pure ZFS /boot solution to get fixed/created.

**Review by zdykstra — APPROVED** [review]

**Pull request merged**
